### ISSUE TITLE
Fontsize [ issue ]

### ISSUE THREAD

**Issue by ananthuthilakan** [nickmilo/Cybertron#18]
changing fontsize doesn't reflect in theme.

**Comment by runoba** [comment]
+1
I would really like to adjust the font size like the default and most other themes.

**Comment by Raynard-Swanepoel** [comment]
+1 So far my favourite theme but not being able to zoom is a bit of a bummer. #16

**Comment by 3T1C** [comment]
> changing fontsize doesn't reflect in theme.

Create your css snippets and add this code to your file.
```css
.cm-s-obsidian {

  font-size: var(--font-text-size);
}
```
