### ISSUE TITLE
Settings modal no longer completely scrollable?

### ISSUE THREAD

**Issue by kiranjholla** [nickmilo/Cybertron#35]
Ever since the recent update to the Cybertron theme, the left navigation items in the settings modal seems to be getting truncated at the bottom with no scrollbar.

Please see the below screenshot:
![image](https://github.com/nickmilo/Cybertron/assets/4491818/07e0c7c8-2cb2-47db-9edd-abf44daf53c6)

In comparison, the same settings modal with the Default theme in Obsidian looks like this:
![image](https://github.com/nickmilo/Cybertron/assets/4491818/f87b50c8-1dec-4828-b9af-9478f554d8d7)

**Comment by kiranjholla** [comment]
I believe the following two changes in the `theme.css` file should fix the issue

Instead of:

```css
.modal.mod-settings .vertical-tab-header {
  height: 90vh;
}

.modal.mod-settings .vertical-tab-content-container {
  height: 90vh;
}
```

we need to update it to:
```css
.modal.mod-settings .vertical-tab-header {
  height: 100%;
}

.modal.mod-settings .vertical-tab-content-container {
  height: 100%;
}
```
